### ISSUE TITLE
Redstone crushing recepie missing

### ISSUE THREAD

**Issue by Sphinx2k** [itsdinkd/AQM2#125]
**Modpack Version**
2.x.x +

**Minecraft Version**
1.18

**Describe the crash or bug**
In version 1.5 of the pack, there was a recipe to crush redstone ore. This is missing in the newer versions of the pack.
So one ore would become 6 crushed dust, that could be further crushed to 1.5x redstone dust. (One ore to ~9 redstone dust)

**Additional context**
For progressing in "Modern Inustrialization" a lot of stainless steel is needed. For crafting and for thinks like the stainless steel drill that is used in the electrical quarry. the only way to get stainless steel is through ruby dust. crushing ruby ore is one way the other is using the centrifuge with redstone ore. But for 3 stainless steel you need 1 ruby dust, for one ruby dust 60 redstone dust is needed. 

Without crushing redstone i can't see a valid way how to progress in this mod.

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/153956902-36ee3b81-e974-4186-b516-3c0f1192deee.png)
It exists.

**Comment by passivagressiv** [comment]
I created a workarround for this issue myself because you cannot automate the mining of nether redstone with the MI quarry

1) open the "saves" folder and the folder with the world you want the recipe to be in

2) open the folder "datapacks"

[redstone_crushed.zip](https://github.com/itsdinkd/AQM2/files/8080722/redstone_crushed.zip)

3) put this folder there and unpack it

start minecraft and it should be working, but with normal redstone ore only not with deepslate redstone ore

**Comment by Sphinx2k** [comment]
Thanks a lot that would be my next question if it was possible to add the recepie myself. 

And yes if it is intended that the player should mine 10.000 or more redstone in the nether by hand thats ok. But the absurde amounds that are needed should be gatherable with the quarry. to get to the better quarry you need this redstone income so this is not an option.

**Comment by passivagressiv** [comment]
I think it is a bug - the recipe is still within the modpack but somehow not used in the game - I just copied it and implemented it with a datapack
