### ISSUE TITLE
[BUG] Modern Industrialization Salt is useless

### ISSUE THREAD

**Issue by TureyLab** [itsdinkd/AQM2#41]
**Modpack Version**
1.3

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Modern Industralisation generates Salt Dust, but we have to use the bewitchment salt for modern industrialization

**Steps to reproduce the behavior:**
Steel drill quarries Salt Ore, 
Recipe for Chlorine uses only Bewitchment Salt, Salt dust useless, Modern Industrialisation Salt Ore even dont show up in REI

**Expected behavior**
Salt Dust is usable

**Comment by itsdinkd** [comment]
This is for unification. Bewitchment is the one and salt in the pack.

**Comment by TureyLab** [comment]
Shouldn‘t the modern industrialization salt ore then not give bewitchment salt (after processing)? The ore is useless and the quarry’s doesn‘t generate bewitchment salt.

**Comment by itsdinkd** [comment]
If there is salt ore generating from MI then its something that was missed as it should be disabled.  From: jschmidtSent: Wednesday, June 8, 2022 2:10 PMTo: itsdinkd/AQM2Cc: itsdinkd; State changeSubject: Re: [itsdinkd/AQM2] [BUG] Modern Industrialization Salt is useless (Issue #41) Shouldn‘t the modern industrialization salt ore then not give bewitchment salt (after processing)? The ore is useless and the quarry’s doesn‘t generate bewitchment salt.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
