### ISSUE TITLE
[BUG] Weird texture glitch on steel macerator (MI)

### ISSUE THREAD

**Issue by Sebas-Re** [itsdinkd/AQM2#51]
**Modpack Version**
1.3.2

**Minecraft Version**
1.18.2

**Describe the crash or bug**
Steel macerator from MI (modern_industrialization:steel_macerator) has this weird texture glitch on current version:

![image](https://user-images.githubusercontent.com/32151264/173873363-5dd48818-1bbb-444b-a1e5-b9d72de59ca6.png)

Currently enabled resourcepacks:
![image](https://user-images.githubusercontent.com/32151264/173873454-2cbac91a-95fd-4709-a1ea-b1d03799dabc.png)

**Comment by itsdinkd** [comment]
Most likely polymer Sent from Mail for Windows From: Sebas-ReSent: Wednesday, June 15, 2022 9:04 AMTo: itsdinkd/AQM2Cc: itsdinkd; AssignSubject: [itsdinkd/AQM2] [BUG] Weird texture glitch on steel macerator (MI) (Issue #51) Modpack Version1.3.2Minecraft Version1.18.2Describe the crash or bugSteel macerator from MI (modern_industrialization:steel_macerator) has this weird texture glitch on current version:Currently enabled resourcepacks:—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>

**Comment by itsdinkd** [comment]
Can you try removing universal graves to see if it fixes it
