### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Damon-Stroud** [itsdinkd/AQM2#89]
Im a bit confused as to using the waystones, what is it asking for?

**Comment by Archiplex** [comment]
You need a gobber globette to use them. They're almost not worth using at all because of this due to the existence of bewitchment portals, and how irritatingly difficult it is to get gobber ore, and how needed it is.

Would absolutely love if it was changed to something else a little more accessible.

**Comment by itsdinkd** [comment]
This isn't used for support.
